Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - advanced-sneakers-activejob.gemspec
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Security/MarshalLoad:
  Exclude:
    - spec/**/*

Security/Eval:
  Exclude:
    - spec/apps/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Lint/SuppressedException:
  Exclude:
    - spec/**/*
